---
name: Checks
on:
    - push
    - workflow_dispatch
jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  node-version: 18
                  cache: npm
            - run: pnpm install
            - run: pnpm run lint
    tsc:
        name: Tsc
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  node-version: 18
                  cache: npm
            - run: pnpm install
            - run: pnpm run tsc
