---
name: Checks
on:
    - push
    - workflow_dispatch
jobs:
    checks:
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            # todo: remove!
            # - name: call hello world
            #   uses: ./.github/workflows/composite/hello-world
            #   with:
            #     who-to-greet: 'Kajendran'
            - name: setup
              uses: ./.github/workflows/setup
            - name: Run EsLint
              run: pnpm run lint
            - name: Run Tsc
              run: pnpm run tsc
