---
name: Checks
on:
    - push
    - workflow_dispatch
jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm
            - run: npm install
            - run: npm run lint
    tsc:
        name: Tsc
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: npm
            - run: npm install
            - run: npm run tsc
