---
name: Checks
on:
    - push
    - workflow_dispatch
jobs:
    checks:
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup CI
              uses: ./.github/workflows/setup-ci
            - name: Run EsLint
              run: pnpm run lint
            - name: Run Tsc
              run: pnpm run tsc
