name: Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    workflow_dispatch:
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
        AUTH0_SECRET: ${{secrets.PROD_ENV_AUTH0_SECRET}}
        AUTH0_BASE_URL: ${{secrets.PROD_ENV_AUTH0_BASE_URL}}
        AUTH0_ISSUER_BASE_URL: ${{secrets.PROD_ENV_AUTH0_ISSUER_BASE_URL}}
        AUTH0_CLIENT_ID: ${{secrets.PROD_ENV_AUTH0_CLIENT_ID}}
        AUTH0_CLIENT_SECRET: ${{secrets.PROD_ENV_AUTH0_CLIENT_SECRET}}
        AUTH0_AUDIENCE: ${{secrets.PROD_ENV_AUTH0_AUDIENCE}}
        AUTH0_SCOPE: ${{secrets.PROD_ENV_AUTH0_SCOPE}}
        API_BASE_URL: ${{secrets.PROD_ENV_API_BASE_URL}}
        NEXT_PUBLIC_IMAGE_CDN_BASE: ${{secrets.PROD_ENV_NEXT_PUBLIC_IMAGE_CDN_BASE}}
        NEXT_PUBLIC_SUPPORT_EMAIL: ${{secrets.PROD_ENV_NEXT_PUBLIC_SUPPORT_EMAIL}}
        NEXT_CONTACT_US_FORM_KEY: ${{secrets.PROD_ENV_NEXT_CONTACT_US_FORM_KEY}}
        NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{secrets.PROD_ENV_NEXT_PUBLIC_RECAPTCHA_SITE_KEY}}
        RECAPTCHA_SITE_SECRET: ${{secrets.PROD_ENV_RECAPTCHA_SITE_SECRET}}
        NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 20.9.0
        uses: actions/setup-node@v2
        with:
            node-version: 20.9.0
      - name: Install pnpm
        run: npm install --global pnpm@8.11.0
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}