name: Build and Lint Checks

on:
    workflow_dispatch:
    # push:
    #   branches:
    #     - main

jobs:
    install-devbox:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.11.0
            - name: Install node modules
              run: devbox run -- pnpm install --frozen-lockfile
    lint:
        runs-on: ubuntu-latest
        needs: install-devbox
        steps:
            - uses: actions/checkout@v4
            - name: Linting
              run: pnpm lint
    build:
        runs-on: ubuntu-latest
        needs: install-devbox
        steps:
            - uses: actions/checkout@v4
            - name: Building
              run: pnpm build
