name: Build and Lint Checks

on:
    workflow_dispatch:
    # push:
    #   branches:
    #     - main
env:
    NODE_OPTIONS: "--max_old_space_size=4096"
    SKIP_ENV_VALIDATION: true
    # AUTH0_SECRET: ${{ secrets.DEV_AUTH0_SECRET }}
    # AUTH0_BASE_URL: "http://localhost:3000"
    # AUTH0_CLIENT_ID: ${{ secrets.DEV_AUTH0_CLIENT_ID }}
    # AUTH0_CLIENT_SECRET: ${{ secrets.DEV_AUTH0_CLIENT_SECRET }}
    # AUTH0_SCOPE: "openid profile email offline_access"
jobs:
    install-devbox:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install devbox
              uses: jetify-com/devbox-install-action@v0.11.0
            - name: Install node modules
              run: devbox run -- pnpm install --frozen-lockfile
    lint:
        runs-on: ubuntu-latest
        needs: install-devbox
        steps:
            - uses: actions/checkout@v4
            - name: Linting
              run: pnpm lint
    build:
        runs-on: ubuntu-latest
        needs: install-devbox
        steps:
            - uses: actions/checkout@v4
            - name: Building
              run: pnpm build
