---
name: Storybook tests
on:
    workflow_dispatch:
jobs:
    test-storybook:
        runs-on: ubuntu-latest
        env:
            SKIP_ENV_VALIDATION: true
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup CI
              uses: ./.github/workflows/setup-ci
            - name: Install Playwright
              run: pnpm exec playwright install --with-deps chromium
            - name: Install global dependencies
              run: pnpm install -g concurrently wait-on
            - name: Serve Storybook and run tests
              run: |
                  npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
                    "pnpm storybook --port 6006" \
                    "npx wait-on tcp:6006 && pnpm test-storybook"
