name: Playwright Tests (temp)
on:
    workflow_dispatch:
env:
  Auth0__ClientId: ${{ secrets.DEV_API_AUTH0_CLIENT_ID }}
  Auth0__ClientSecret: ${{ secrets.DEV_API_CLIENT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_API_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_API_AWS_SECRET_ACCESS_KEY }}
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.29.2'
    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.READ_PKG_GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: ${{ secrets.READ_PKG_GITHUB_TOKEN }}
    - name: Pull docker images
      run: docker-compose -f "./.github/workflows/test-api-db/docker-compose.yml" pull
    - name: Run docker images
      run: docker-compose -f "./.github/workflows/test-api-db/docker-compose.yml" up -d
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    - name: Down docker images
      run: docker-compose -f "./.github/workflows/test-api-db/docker-compose.yml" down
