name: Playwright Tests (temp)
on:
    workflow_dispatch:
env:
  Auth0__ClientId: ${{ secrets.DEV_API_AUTH0_CLIENT_ID }}
  Auth0__ClientSecret: ${{ secrets.DEV_API_CLIENT_SECRET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.DEV_API_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_API_AWS_SECRET_ACCESS_KEY }}
  TEST_ADMIN_EMAIL: ${{ secrets.DEV_TEST_ADMIN_EMAIL }}
  TEST_ADMIN_PASSWORD: ${{ secrets.DEV_TEST_ADMIN_PASSWORD }}
  TEST_ADMIN_ID: ${{ secrets.DEV_TEST_ADMIN_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DEV_PROJECT_ID }}
  API_BASE_URL: "http://localhost:5002/api"
  NODE_OPTIONS: "--max_old_space_size=4096"
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup CI
      uses: ./.github/workflows/setup-ci
    - uses: KengoTODA/actions-setup-docker-compose@main
      with:
        version: '1.29.2'
    - name: Login to GitHub Container registry
      uses: docker/login-action@v1
      env:
        GITHUB_USER: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.READ_PKG_GITHUB_TOKEN }}
      with:
        registry: ghcr.io
        username: $GITHUB_USER
        password: ${{ secrets.READ_PKG_GITHUB_TOKEN }}
    - name: Pull docker images
      run: docker-compose -f "./.github/workflows/test-api-db/docker-compose.yml" pull
    - name: Run docker images
      run: docker-compose -f "./.github/workflows/test-api-db/docker-compose.yml" up -d
    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash
    - name: Pull configs into .env file
      run: vercel env pull .env --token=${{ secrets.VERCEL_TOKEN }}
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps firefox
    - name: Build webapp
      run: pnpm build
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - name: Down docker images
      run: docker-compose -f "./.github/workflows/test-api-db/docker-compose.yml" down
